Made errors and information less verbose.
Added info and errquit functions to make messages less verbose unless -v
option enabled. This should make it easier for students to implement
error checking, etc., without having to match specific error messages.

diff --git a/randomchunk b/randomchunk
--- a/randomchunk
+++ b/randomchunk
@@ -12,34 +12,54 @@ minsize=0
 maxsize=""
 randomsize=0
 append=""
+VERBOSE=0
+
+function errquit 
+{
+	if [[ $VERBOSE == 1 ]]
+	then
+		echo $@
+	else
+		echo "Error"
+	fi
+	exit 1
+}
+
+function info
+{
+	if [[ $VERBOSE == 1 ]]
+	then
+		echo $@
+	fi
+}
 
 # use getopts to collect parameters
-while getopts "i:o:s:n:x:p:raq" OPTION
+while getopts "i:o:s:n:x:p:raqv" OPTION
 do
   case $OPTION in
 	i)
 	  infile="$OPTARG"
-	  echo "Input file is: '$infile'"
+	  info "Input file is: '$infile'"
 	  ;;
 	o)
 	  outfile=$OPTARG
-	  echo "Output file is: '$outfile'"
+	  info "Output file is: '$outfile'"
 	  ;;
 	s)
 		size=$((OPTARG))
-	  echo "Chunk size is: '$size'"
+	  info "Chunk size is: '$size'"
 	  ;;
 	n)
 		minsize=$((OPTARG))
-	  echo "Min chunk size is: '$minsize'"
+	  info "Min chunk size is: '$minsize'"
 	  ;;
 	x)
 		maxsize=$((OPTARG))
-	  echo "Max chunk size is: '$maxsize'"
+	  info "Max chunk size is: '$maxsize'"
 	  ;;
 	r)
 	  randomsize=1
-	  echo "A random-sized subset of the file will be chosen."
+	  info "A random-sized subset of the file will be chosen."
 	  ;;
 	a)
 	  append="conv=notrunc oflag=append"
@@ -53,6 +73,11 @@ do
 	    #seeding with non-numeric values always yields 20034 
 	    seed="$OPTARG"
 	    RANDOM="$seed"
+		;;
+	v)
+		# enable verbose mode
+		VERBOSE=1
+		;;
   esac
 done
 
@@ -69,6 +94,7 @@ then
 	echo "	-x		maximum size for -r (in KB)"
 	echo "	-a		append to ouput file rather than overwriting"
 	echo "	-q		if file is not large enough, just copy entire file"
+	echo "	-v		be verbose"
 	echo ""
   exit 1
 fi
@@ -80,20 +106,21 @@ if [ ! -z $size ]
 then
 	if (( $size < 0 ))
 	then
-	  echo "Size cannot be negative. ($size)"
+	  errquit "Size cannot be negative. ($size)"
 	elif (( $size > $infilesize ))
 	then
 		if [[ $ok_if_short == 1 ]]
 		then
-			echo "File is too small for this size so we will copy the whole thing. (-q)"
+			info "File is too small for this size so we will copy the whole thing. (-q)"
 			cp -v "$infile" $outfile
 			exit 0
 		fi
-	  echo "Size ${size}K requested, but '$infile' is only ${infilesize}K bytes, aborting." 1>&2
-	  exit 1
+
+	  errquit "Size ${size}K requested, but '$infile' is only ${infilesize}K bytes, aborting." 1>&2
+
 	elif (( $minsize > 0 )) || [ ! -z $maxsize ] || [[ $randomsize == 1 ]]
 	then
-  		echo "WARNING: explicit size argument (${size}K) OVERRIDES random/min/max settings."
+  		info "WARNING: explicit size argument (${size}K) OVERRIDES random/min/max settings."
 	fi
 fi
 
@@ -101,12 +128,10 @@ if [ ! -z $maxsize ]
 then
 	if (( $maxsize > $infilesize ))
 	then
-	  echo "Maxsize ${maxsize}K is greater than ${infilesize}K, aborting." 1>&2
-	  exit 1
+	  errquit "Maxsize ${maxsize}K is greater than ${infilesize}K, aborting." 1>&2
 	elif (( $minsize > $maxsize ))
 	then
-	  echo "Minsize (${minsize}K) cannot be larger than maxsize (${maxsize}K), aborting." 1>&2
-	  exit 1
+	  errquit "Minsize (${minsize}K) cannot be larger than maxsize (${maxsize}K), aborting." 1>&2
 	fi
 else
   maxsize=$infilesize
@@ -114,20 +139,17 @@ fi
 
 if (( $minsize < 0 ))
 then
-  echo "Minsize (${minsize}K) cannot be negative, aborting." 1>&2
-  exit 1
+  errquit "Minsize (${minsize}K) cannot be negative, aborting." 1>&2
 fi
 
 if [ -f "$infile" ]
 then
 	if [ ! -r "$infile" ]
 	then
-	  echo "Infile '$infile' exists but is not readable." 1>&2
-	  exit 1
+	  errquit "Infile '$infile' exists but is not readable." 1>&2
 	fi
   else
-	  echo "Infile '$infile' does not exist." 1>&2
-	  exit 1
+	  errquit "Infile '$infile' does not exist." 1>&2
 fi
 
 if [[ $randomsize == 1 ]]
@@ -138,11 +160,11 @@ then
 		size=$(( RANDOM % infilesize ))
 	done
   	
-	echo "Random size: ${size}K"
+	info "Random size: ${size}K"
 fi
 
 skip=$(( RANDOM % ( infilesize - size ) ))
-echo "Skipping $skip KB out of $infilesize and reading $size KB to $outfile"
+info "Skipping $skip KB out of $infilesize and reading $size KB to $outfile"
 if dd if="$infile" of=$outfile bs=1024 count=$size skip=$skip $append 2>&1
 then
 	hash=$(sha256sum $outfile | cut -d " " -f 1)
